// Temperate bestiary batch (DEC-071 items 1 and 5; DEC-072 frames). Source list: temperate_list.json (adopted bestiary NAT.07.01 x SRD 5.1
// sizes), commonest first. v3 for humanoid shapes (sizes: Small 52 -> ~48 tall, Medium 76 -> ~72, Large 96 -> ~90 inside 48 wide,
// Huge 100 -> inside 96x96); Pro for everything else (Tiny/Small 32-40, Medium 44-64, Large long 72-96 in a 96x96 frame: DEC-072 amendment, ART-SCALE-1b).
const T = " Classic 1990s RPG pixel art in the style of Ultima VII, English folklore flavour, high top-down view, lit from the upper left, highly detailed, crisp pixel clusters, selective outline in its own darkest colours (no black outline), restrained natural earthy colours, standing still, no ground, no shadow, no text.";
const NARROW = " Upright, arms close to its sides, a narrow silhouette.";
const V = (tag, size, d) => ({ tag, args: { name: "DEUS " + tag, description: d + T, mode: "v3", size, view: "high top-down", outline: "selective outline", detail: "high detail" } });
const Q = (tag, template, size, d) => ({ tag, args: { name: "DEUS " + tag, description: d + T, body_type: "quadruped", template, mode: "pro", size, view: "high top-down" } });
const P = (tag, size, d) => ({ tag, args: { name: "DEUS " + tag, description: d + T, mode: "pro", size, view: "high top-down" } });
module.exports = [
  // ---- Owner 2026-10-01: "Ice wraith should look ghostlier" ----
  V("ice-wraith3", 68, "An ice wraith of the frozen north, a ghost: a translucent spectral figure of pale blue-white frost light, see-through in places, a hooded shroud of drifting rime with no solid body inside, hollow dark eye-holes with a cold blue glow, thin ghostly clawed hands at its sides, its lower body dissolving into trailing wisps of frost mist." + NARROW),
  // ---- v3 humanoid shapes, commonest first ----
  V("goblin", 52, "A goblin, a small hob-cousin of hedge and barrow: wiry grey-green skin, long pointed ears, sharp yellow eyes, ragged brown leather jerkin, a crude knife at its belt, bare feet."),
  V("grimlock", 76, "A grimlock, blind cave-folk: grey stony skin, eyeless smooth face, lank black hair, muscular stooped body, a loincloth of hide, a stone-headed club in one hand."),
  V("kobold", 52, "A kobold, small knocker-kin of the mines: rust-red scaly skin, small horns, a dog-like reptile snout, a tail, a tattered miner's tunic, a little pick in one hand."),
  V("skeleton", 76, "A skeleton raised from a barrow: old yellowed bones, empty eye sockets, scraps of a rotted tunic and a rusted short sword in one hand."),
  V("ghoul", 76, "A ghoul, a grave-eater: grey-blue emaciated skin, long clawed fingers, a lipless mouth of sharp teeth, burial rags, crouched and hungry."),
  V("bugbear", 80, "A bugbear, shaggy boggart-kin of the wood-edge: a hulking hairy goblinoid with coarse brown fur, a bear-like face, long arms, a hide jerkin and a spiked wooden club."),
  V("duergar", 64, "A duergar, a pale knocker-lord of the deep mines: a stocky grey-skinned dwarf with a bald head, a long iron-grey beard, dark iron armour and a war pick."),
  V("ghast", 76, "A ghast, a barrow-ghoul: a gaunt greenish-grey corpse with long claws, glowing pale eyes, torn grave clothes, a faint green haze of stench about it."),
  V("svirfneblin", 52, "A deep gnome of the under-hedge: a small stone-grey gnome with a bald head, large nose and ears, a leather jerkin and a miner's pick."),
  V("hobgoblin", 76, "A hobgoblin of the border woods: a tall disciplined goblinoid with orange-red skin, a red cap, a mail shirt over a dark red tunic, a round shield and a longsword."),
  V("orc", 76, "An orc of the untamed marches: grey-green skin, tusks, a heavy brow, wild black hair, crude hide and fur armour, a greataxe."),
  V("satyr", 76, "A satyr, a puck-kin piper of the fairy ring: a man's upper body with curled ram horns and a beard, shaggy goat legs and hooves, holding reed pipes."),
  V("shadow", 76, "A shadow, an unattached shade: a dark featureless humanoid silhouette of smoky black, thin wisps trailing from its edges, two faint pale eyes."),
  V("specter", 76, "A specter, an angry shade torn loose by a violent death: a translucent pale grey-blue ghostly figure with a gaping mouth and clawed hands, its lower body fading into mist."),
  V("wererat", 76, "A wererat in hybrid form: a hunched rat-headed man with brown fur, long whiskers and a naked tail, wearing a ragged cellar-worker's tunic, holding a short blade."),
  V("dryad", 76, "A dryad, a tree-bound fair one of oak and thorn: a tall slender woman with bark-brown skin, hair of green oak leaves and ivy, a simple dress of leaves."),
  V("ettercap", 76, "An ettercap, a web-tending wood-horror: a hunched spidery humanoid with dark purple-brown chitinous skin, long clawed fingers, mandibles and a small cluster of eyes."),
  V("gargoyle", 76, "A gargoyle, a stone watcher of tor and ruin: a grey stone winged humanoid with horns, a grotesque church-carving face, folded bat wings, clawed feet." + NARROW),
  V("harpy", 76, "A harpy, a clifftop singer: a woman's upper body with wild dark hair, brown feathered wings for arms folded at its sides, and the scaled legs and talons of a vulture."),
  V("animated-armor", 76, "Animated armour, a barrow harness that walks without a wearer: an empty suit of dark tarnished plate armour with a closed helm, dark empty gaps between the plates."),
  V("ogre", 96, "An ogre, a man-eating giant of isolated holdings: a very tall heavy brute with dull yellow-brown skin, a small head with a heavy jaw, a hide loincloth, a big wooden club." + NARROW),
  V("ogre-zombie", 96, "An ogre zombie, a dead ogre that has not lain down: a very tall rotting grey-green brute, slack jaw, torn hide loincloth, patches of bare bone." + NARROW),
  V("minotaur-skeleton", 96, "A minotaur skeleton, labyrinth bones still walking: a very tall skeleton of a bull-headed man with long horns on its skull, old yellowed bones, a rusted greataxe." + NARROW),
  V("ettin", 96, "An ettin, a two-headed hill-giant of the broken ridges: a very tall brute with two ugly bearded heads, filthy hide clothing and a spiked club." + NARROW),
  V("ghost", 76, "A ghost bound to a particular place: a pale translucent white-blue figure of a long-dead person in old-fashioned clothes, sorrowful face, its lower body fading into mist."),
  V("werewolf", 80, "A werewolf in hybrid form: a tall man-wolf with grey-brown fur, a wolf's head and muzzle, long clawed arms, tattered breeches." + NARROW),
  V("wight", 76, "A barrow-wight keeping its grave-goods: a withered corpse with grey leathery skin and pinpoint red eyes, wearing ancient corroded bronze armour and a cloak, holding an old sword."),
  V("hill-giant", 100, "A hill giant of the standing-stone country: an enormous dim brute with ruddy skin, a heavy belly, wild hair, hides and furs, a tree-trunk club."),
  V("doppelganger", 76, "A doppelganger in its true form: a lean grey hairless humanoid with blank pale eyes and an unfinished smooth face, long thin fingers."),
  V("flesh-golem", 80, "A flesh golem, stitched corpse-work from a workshop: a tall patchwork body of mismatched grey and pink skin sewn with thick black stitches, iron bolts in the neck, ragged trousers."),
  V("green-hag", 76, "A green hag, a fen-crone of the will-o-wisp bogs: a hunched old woman with mottled green skin, long tangled black hair, a hooked nose, long claws, a ragged dark shawl."),
  V("medusa", 76, "A medusa, a stone-gaze guardian of sealed barrow halls: a woman with green scaled skin and a head of living green snakes for hair, a dark robe, glowing eyes."),
  V("minotaur", 96, "A minotaur of the labyrinthine underways: a very tall bull-headed man with long horns, dark brown fur on its head and shoulders, a muscular body, a loincloth and a greataxe." + NARROW),
  V("vampire-spawn", 76, "A vampire spawn, newly bound hungry dead: a pale gaunt man with dark-ringed red eyes, sharp fangs, dirty torn fine clothes."),
  V("werebear", 84, "A werebear in hybrid form: a tall man-bear with thick brown fur, a bear's head, huge clawed paws, the remains of a woodsman's shirt." + NARROW),
  V("wereboar", 80, "A wereboar in hybrid form: a stocky man-boar with bristly dark grey-brown hide, a boar's head with tusks, a ragged leather vest."),
  V("wraith", 76, "A wraith, a cold shade of a life emptied of warmth: a tall hooded figure of tattered black cloth with no visible body, two cold glowing eyes, ghostly clawed hands."),
  V("clay-golem", 96, "A clay golem shaped for a barrow or well: a tall heavy figure of grey-brown fired clay with crude features and old runes carved on its chest." + NARROW),
  V("shield-guardian", 96, "A shield guardian, a bound construct: a tall armoured construct of iron plates and wood with a featureless helm-like head and a large amulet socket in its chest." + NARROW),
  V("stone-giant", 100, "A stone giant of tor and cliff: an enormous lean grey-skinned giant with stony features, bald head, simple stone-coloured hide clothing, holding a boulder."),
  V("stone-golem", 96, "A stone golem, a standing stone given a walking purpose: a tall blocky figure of grey granite with a carved face and lichen in its cracks." + NARROW),
  V("cloud-giant", 100, "A cloud giant of the clouded peaks: an enormous noble giant with pale blue-grey skin, silver hair and beard, fine pale robes and a silver circlet."),
  V("iron-golem", 96, "An iron golem, a forge-built watcher of a sealed hold: a tall armoured figure of dark riveted iron with a horned helm-head and glowing furnace-orange eyes." + NARROW),
  V("lich", 76, "A lich, a barrow-king who refused the last ending: a skeletal sorcerer with dried skin on its skull, glowing pinpoint eyes, a tattered dark royal robe and an old crown."),
  V("vampire", 76, "A vampire bound to a particular earth: a tall pale aristocrat with dark slicked hair, red eyes, fangs, a high-collared black cloak over fine dark clothes."),
  V("earth-elemental", 96, "An earth elemental, awakened stone walking from a prepared seam: a tall hulking humanoid shape of packed earth, rock and stones, with glowing amber eye-gaps." + NARROW),
  V("sprite", 28, "A sprite, thumb-high fair folk of ring and hollow hill: a tiny slender winged fairy person with dragonfly wings, green and brown clothing of leaves, a tiny bow."),
  // ---- Pro, commonest first ----
  P("axe-beak", 72, "An axe beak, a flightless plains bird, a non-humanoid animal: a tall long-legged grey-brown bird with tiny wings and a huge axe-shaped hooked beak."),
  Q("badger", "bear", 32, "A European badger: a low stocky grey body, short legs, a black and white striped face."),
  Q("draft-horse", "horse", 96, "A heavy draft horse of the lowland: a huge muscular bay horse with feathered white hooves, a dark mane and tail, no tack."),
  P("eagle", 40, "A golden eagle, a non-humanoid bird of prey in flight with broad wings spread wide: dark brown feathers with a golden nape, hooked yellow beak."),
  Q("elk", "horse", 96, "An elk of upland wood: a large dark brown deer with a pale rump, a long face and broad flat palmate antlers."),
  P("frog", 32, "A common frog, a non-humanoid animal sitting: an olive-green and brown mottled frog with long folded hind legs and golden eyes."),
  Q("giant-badger", "bear", 48, "A giant badger: a big low stocky grey badger with a black and white striped face, long digging claws."),
  P("giant-bat", 72, "A giant bat, a non-humanoid animal in flight with huge leathery wings spread wide: dark brown fur, black wings with finger bones, large ears, small fangs."),
  P("giant-centipede", 56, "A giant centipede, a non-humanoid animal: a long segmented red-brown body with many yellow legs, venomous mandibles, coiled in an S on the ground."),
  P("giant-fire-beetle", 40, "A giant fire beetle, a non-humanoid insect: a dark red-brown armoured beetle with two softly glowing orange glands above its eyes and one near its abdomen."),
  P("giant-frog", 48, "A giant frog, a non-humanoid animal sitting: a large mottled green and brown frog with a wide mouth and long folded legs."),
  P("giant-poisonous-snake", 48, "A giant adder, a non-humanoid legless snake coiled with its head raised: grey-brown scales with a bold dark zigzag along the back."),
  Q("giant-rat", "cat", 40, "A giant rat: a dog-sized brown rat with greasy fur, yellow teeth, small eyes and a long naked tail."),
  Q("giant-weasel", "dog", 48, "A giant weasel: a long lithe red-brown weasel with a cream belly and a short dark-tipped tail."),
  P("giant-wolf-spider", 48, "A giant wolf spider, a non-humanoid animal: a hairy brown and grey striped spider with eight long legs and a cluster of shining dark eyes."),
  Q("goat", "horse", 44, "A wild goat of hill and crag: a shaggy grey-brown goat with a beard and long backward-curving horns."),
  P("lizard", 32, "A common lizard, a non-humanoid animal: a small brown-green lizard with a long tail, sprawled legs, sunning itself."),
  Q("mastiff", "dog", 48, "A mastiff of settled halls: a big heavy fawn dog with a black muzzle and drooping jowls, a plain leather collar."),
  Q("mule", "horse", 72, "A mule of road and hill-track: a brown mule with long ears, a short upright mane, a thin tail, no tack."),
  P("owl", 32, "A tawny owl, a non-humanoid bird perched with wings folded: a round brown mottled owl with a pale facial disc and dark eyes."),
  Q("pony", "horse", 64, "A hill pony of moor and pasture: a small sturdy bay pony with a thick dark mane and tail, no tack."),
  P("raven", 32, "A raven, a non-humanoid bird standing on the ground: glossy black feathers, a heavy black beak, shaggy throat feathers."),
  P("shrieker", 40, "A shrieker, an alarm-fungus of the dark damp halls: a man-high pale purple-grey mushroom with a broad spotted cap and a thick stalk, a non-humanoid fungus."),
  P("stirge", 32, "A stirge, a blood-bat of marsh and gorge, a non-humanoid flying creature: a rust-brown bat-winged body with four thin legs and a long needle proboscis."),
  P("violet-fungus", 40, "A violet fungus, a lashing cave-fungus: a squat purple mushroom with several long whip-like purple tendrils, a non-humanoid fungus."),
  Q("weasel", "dog", 32, "A weasel: a tiny long red-brown weasel with a cream belly and short tail."),
  P("darkmantle", 40, "A darkmantle, a stalactite-skin that drops upon miners: a dark grey squid-like body with a stony domed top and a skirt of short tentacles joined by a web, a non-humanoid creature."),
  Q("giant-goat", "horse", 76, "A giant goat of crag and snowfield: a huge shaggy white-grey goat with long curling horns and a beard."),
  P("gray-ooze", 40, "A gray ooze, a wet-rock slough mistaken for a puddle: a low glistening grey puddle-shaped blob of slime, a non-humanoid ooze."),
];
