// Registers the world-build plugins in game/js/plugins.js in the order docs/design/WORLD_ARCHITECTURE.md §5 gives,
// keeping every existing entry and its parameters. Run only with the RMMZ editor closed (ENGINE_RULES §3).
// Usage: node tools/register_world_plugins.js [--game <game folder>] [--dry]
"use strict";
const fs = require("fs");
const path = require("path");

const args = process.argv.slice(2);
const gameIdx = args.indexOf("--game");
const gameDir = path.resolve(gameIdx >= 0 ? args[gameIdx + 1] : path.join(__dirname, "..", "game"));
const file = path.join(gameDir, "js", "plugins.js");
const dry = args.includes("--dry");
// The order after UF_ProcGen. Entries not yet on disk are skipped with a warning.
const ORDER = ["DEUS_World", "DEUS_WorldGen", "DEUS_Tiles", "DEUS_Factions", "DEUS_History", "DEUS_Objects", "DEUS_Doors", "DEUS_Items", "DEUS_Jobs", "DEUS_Floors",
    "DEUS_Colonists", "DEUS_Wildlife", "DEUS_Stance", "DEUS_Combat", "DEUS_Anim", "DEUS_Fog", "DEUS_DayNight", "DEUS_TimeSpeed", "DEUS_Camera", "DEUS_Speech", "UF_Skills", "DEUS_Look", "DEUS_Interact", "DEUS_Sheet", "DEUS_Talk", "DEUS_Fire", "DEUS_Test"];
// DEUS_Combat is listed so the tool keeps it where it already sits in plugins.js (after DEUS_Stance); entries not in ORDER
// are moved in front of DEUS_World. DEUS_Anim loads after DEUS_Combat (its @orderAfter); DEUS_Sheet after DEUS_Interact.
// DEUS_Talk and DEUS_Fire load after DEUS_Interact (both wrap it at runtime); DEUS_Fire is also after DEUS_Objects, DEUS_Items, DEUS_Jobs.
// DEUS_Speech loads after DEUS_Visuals (in front of DEUS_World) and DEUS_Camera (its @orderAfter), before DEUS_Look and DEUS_Talk.
// UF_Skills loads after DEUS_Jobs, DEUS_Colonists, DEUS_Combat and DEUS_Speech (its @orderAfter), before DEUS_Look (VISION V63).
const DESCRIPTIONS = {
    DEUS_Tiles: "[UF Tiles] Ground kinds drawn in code and the runtime world tileset (91).",
    DEUS_Objects: "[UF Objects] Per-cell world objects (plants, stones, buildings): drawing, passability, actions, regrowth.",
    DEUS_Doors: "[UF Doors] Faction-aware site and house doors: passage, building, interaction, and damage.",
    DEUS_Items: "[UF Items] Items on the ground, in stacks and in inventories.",
    DEUS_Jobs: "[UF Jobs] DF-style jobs: walk to a target, work, change the world (gather, chop, haul, build, craft, hunt...).",
    DEUS_Floors: "[UF Floors] Enclosed rooms, cultural floor jobs, ground autotiles, and room value.",
    DEUS_Colonists: "[UF Colonists] The pair as world units: needs, personality, daily pattern, the society plan.",
    DEUS_Wildlife: "[UF Wildlife] Creatures spawned with the map by biome; wander and flee.",
    DEUS_Stance: "[UF Stance] Green / yellow / red squares under units by stance toward the colony.",
    DEUS_Combat: "[UF Combat] Real-time combat on the map in ticks: accuracy and defence rolls, max hits, attack speeds, combat styles, attack modes, hitsplats and health bars.",
    DEUS_Anim: "[UF Anim] Attack, hurt and death animations for every person, animal and monster; the remains lie on the ground for a while.",
    DEUS_Speech: "[UF Speech] Remarks, barks, shouts, orders and thoughts float as plain text above the speaker's head (VISION V62).",
    UF_Skills: "[UF Skills] Every person has skills (trades and the fighting skills) that level from 1 to 99 by doing them; higher levels work faster, yield more and make better things.",
    DEUS_Look: "[UF Look] Look label under the mouse: what's there, biome, art file and its status.",
    DEUS_Interact: "[UF Interact] Right-click anything for its interaction options; choices become jobs.",
    DEUS_Sheet: "[UF Sheet] Left-click anything in the world: a panel shows its inventory grid, equipment, face and stats, or its contents and state.",
    DEUS_Talk: "[UF Talk] Right-click a person and choose Talk: a portrait, their line and keywords to click. The world pauses while it is open.",
    DEUS_Fire: "[UF Fire] Fire spreads cell to cell by catalog rules and burns out; it hurts units; colonists carry water to put it out."
};

const text = fs.readFileSync(file, "utf8").replace(/^﻿/, "");
const list = JSON.parse(text.slice(text.indexOf("["), text.lastIndexOf("]") + 1));
const byName = new Map(list.map(p => [p.name, p]));
const pluginsDir = path.join(gameDir, "js", "plugins");

const before = list.filter(p => !ORDER.includes(p.name));
const ordered = [];
for (const name of ORDER) {
    if (!fs.existsSync(path.join(pluginsDir, `${name}.js`))) {
        console.warn(`skip ${name}: no game/js/plugins/${name}.js`);
        continue;
    }
    const existing = byName.get(name);
    ordered.push(existing || { name, status: true, description: DESCRIPTIONS[name] || `[${name}]`, parameters: {} });
}
const result = [...before, ...ordered];
const out = `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n${result.map(p => JSON.stringify(p)).join(",\n")}\n];\n`;
console.log(result.map(p => p.name).join(" > "));
if (dry) {
    console.log("(dry run: nothing written)");
} else {
    fs.writeFileSync(file, out);
    console.log(`wrote ${file} (${result.length} plugins)`);
}
