#!/usr/bin/env node
"use strict";

// tools/test_lazy_area_generation.js — WG.CELL-WRITE lane-dd (WG.00.46).
// New Game generates the start area only. Other areas are generated by the request
// that needs their floor. Per-area core checksums, one levels:areaGenerated per
// world state, held across a load until World.state is restored.
//
// Exit 0: every check that ran passed. Exit 1: a named check failed (a caught
// mutant exits 1). Exit 2: the harness itself broke, or the mutant name is unknown.
// --mutant=<name> runs only the checks that must catch that mutant.
// --capture-fixture writes tools/fixtures/levels/area_checksums_gen5_3x3.json
// after the all-area chain matches lane-dc. It refuses a mutant.
// --from-rev=<sha> loads that revision of DEUS_Levels.js (fail-before). No mutant.

const fs = require("fs");
const path = require("path");
const vm = require("vm");
const { performance } = require("perf_hooks");
const { execFileSync } = require("child_process");
const simHook = require("./lib/vm_sim_require");

const ROOT = path.resolve(__dirname, "..");
const PLUGINS = path.join(ROOT, "game", "js", "plugins");
const LEVELS_FILE = path.join(PLUGINS, "DEUS_Levels.js");
const DC_FIXTURE = path.join(ROOT, "tools", "fixtures", "levels", "core_checksums_gen1_5.json");
const AREA_FIXTURE = path.join(ROOT, "tools", "fixtures", "levels", "area_checksums_gen5_3x3.json");
const TARGET_S = 600;
const CORE = [-2, -1, 0, 1, 2];
const NEW_GAME_PLUGINS = ["DEUS_Core", "DEUS_World", "DEUS_WorldGen", "DEUS_Factions", "DEUS_History", "DEUS_Levels", "DEUS_Dnd5e", "DEUS_Callings", "DEUS_HistoricalDemographics"];
const LEVELS_PLUGINS = ["DEUS_Core", "DEUS_World", "DEUS_WorldGen", "DEUS_Levels"];

const capture = process.argv.includes("--capture-fixture");
const mutant = (process.argv.find(a => a.startsWith("--mutant=")) || "").slice("--mutant=".length);
const fromRev = (process.argv.find(a => a.startsWith("--from-rev=")) || "").slice("--from-rev=".length);

const MUTANTS = {
    regenerate_twice: {
        from: "stats.areaGenerations.push({ ax: ax, ay: ay, gen: g, ms: ms }); // WG.00.46 one generation record",
        to: "stats.areaGenerations.push({ ax: ax, ay: ay, gen: g, ms: ms }); // WG.00.46 one generation record\n        const duplicateStarted = performance.now();\n        volumes.clear(); baselines.clear();\n        generateBaseline(st.seed, g, 0, ax, ay, st.size, st);\n        stats.areaGenerations.push({ ax: ax, ay: ay, gen: g, ms: performance.now() - duplicateStarted });",
        checks: ["new_game_3x3_cost_bound", "new_game_3x3_areas_attributed"]
    },
    eager_ensure: {
        from: "baseline(0, sa.x, sa.y);",
        to: "for (let ay2 = 0; ay2 < st.areasY; ay2++) for (let ax2 = 0; ax2 < st.areasX; ax2++) baseline(0, ax2, ay2);",
        checks: ["ensure_generates_start_area_only"]
    },
    event_per_cache_fill: {
        from: "if (!hadRecord) emitAreaGenerated(ax, ay, g); // WG.00.46 once per world state",
        to: "if (causedGen) emitAreaGenerated(ax, ay, g); // WG.00.46 once per world state",
        checks: ["area_generated_event_once"]
    },
    event_not_held: {
        from: "if (areaEventHold > 0) { // WG.00.46 hold events until the load flush",
        to: "if (false) { // WG.00.46 hold events until the load flush",
        checks: ["area_generated_deferred_on_load"]
    },
    record_not_saved: {
        from: "L.areaSums[sumKey] = sum; // WG.00.46 save the area sum",
        to: "void sum; // WG.00.46 save the area sum",
        checks: ["per_area_checksum_on_first_generation"]
    },
    silent_replace: {
        from: "if (prev !== sum) { // WG.00.46 report, never replace",
        to: "if (prev !== sum) { L.areaSums[sumKey] = sum; // WG.00.46 report, never replace",
        checks: ["per_area_checksum_mismatch_reported"]
    },
    order_dependent_noise: {
        from: "const key = `${seed}:${ax},${ay}:${size}:${d.width}x${d.height}`;",
        to: "const key = `${seed}:${size}:${d.width}x${d.height}`;",
        checks: ["lazy_equals_eager"]
    },
    view_gated_generation: {
        from: "// WG.00.46 view never gates generation",
        to: "// WG.00.46 view never gates generation\n        if (typeof World().viewLevel === \"function\") { const v = World().viewLevel(); if (v && (v.x !== ax || v.y !== ay)) return null; }",
        checks: ["offscreen_request_generates_area"]
    },
    legacy_migration_skipped: {
        from: "if (anySums || !anyString || mismatch) return false;",
        to: "if (true) return false;",
        checks: ["legacy_multi_area_migrates_after_verify"]
    }
};

function harnessDie(msg) {
    console.error("HARNESS " + msg);
    process.exit(2);
}

if (mutant && !MUTANTS[mutant]) harnessDie("unknown mutant " + mutant);
if (mutant && capture) harnessDie("--capture-fixture refuses a mutant");
if (mutant && fromRev) harnessDie("--from-rev and --mutant together are refused");

function shouldRun(name) {
    if (!mutant) return true;
    return MUTANTS[mutant].checks.indexOf(name) >= 0;
}

function levelsSource() {
    let source;
    if (fromRev) {
        source = execFileSync("git", ["show", fromRev + ":game/js/plugins/DEUS_Levels.js"], { cwd: ROOT, encoding: "utf8" });
    } else {
        source = fs.readFileSync(LEVELS_FILE, "utf8");
    }
    if (!mutant) return source;
    const spec = MUTANTS[mutant];
    const hits = source.split(spec.from).length - 1;
    if (hits !== 1) harnessDie("mutant " + mutant + " anchor found " + hits + " times");
    return source.replace(spec.from, () => spec.to);
}

const LEVELS_SRC = levelsSource();
const dcFixture = JSON.parse(fs.readFileSync(DC_FIXTURE, "utf8"));

function dcChain(seed, areas) {
    const found = (dcFixture.cases || []).find(c => c.gen === 5 && c.seed === seed && c.areasX === areas && c.areasY === areas);
    if (!found) harnessDie("lane-dc fixture has no gen5 " + areas + "x" + areas + " seed " + seed);
    return found.checksums;
}

function tilemapStatics() {
    const core = fs.readFileSync(path.join(ROOT, "game", "js", "rmmz_core.js"), "utf8");
    const start = core.indexOf("Tilemap.TILE_ID_B = 0;");
    const table = core.indexOf("Tilemap.WATERFALL_AUTOTILE_TABLE = [");
    const end = core.indexOf("];", table) + 2;
    if (start < 0 || table < 0 || end < 2) throw new Error("rmmz_core.js Tilemap statics not found");
    return "function Tilemap() {}\n" + core.slice(start, end);
}

const TILEMAP_SRC = tilemapStatics();
const catalog = JSON.parse(fs.readFileSync(path.join(ROOT, "game", "data", "UF_WorldCatalog.json"), "utf8"));

function readPlugin(name) {
    if (name === "DEUS_Levels") return LEVELS_SRC;
    return fs.readFileSync(path.join(PLUGINS, name + ".js"), "utf8");
}

function makeEnv(areas, names, beforePlugins) {
    const warnings = [];
    const errors = [];
    const env = {
        window: null, UF: {}, DEUS: {}, Math, performance,
        $ufWorldCatalog: catalog, $deusWorldCatalog: catalog,
        PluginManager: {
            parameters(name) {
                if (name === "DEUS_World" || name === "UF_World") return { AreasX: String(areas), AreasY: String(areas) };
                return {};
            },
            registerCommand() {}
        },
        DataManager: {
            _databaseFiles: [], onLoad() {}, isBattleTest: () => false, isEventTest: () => false,
            makeSaveContents: () => ({}), extractSaveContents() {}
        },
        Input: { keyMapper: {}, isTriggered: () => false, isPressed: () => false },
        TouchInput: {},
        SceneManager: { _scene: null, goto() {} },
        Graphics: { frameCount: 0, boxWidth: 816, boxHeight: 624, width: 816, height: 624 },
        $gameMap: { _mapId: 0, mapId() { return this._mapId || 0; }, width: () => 256, height: () => 256 },
        $gamePlayer: { x: 0, y: 0, isTransferring: () => false },
        $gameSystem: {}, $gameMessage: { isBusy: () => false },
        $gameScreen: { weatherType: () => "none", weatherPower: () => 0, changeWeather() {} },
        ImageManager: { loadTileset: () => ({}), loadCharacter: () => ({}), isBigCharacter: () => true },
        Utils: { isOptionValid: () => false, encodeURI: s => s },
        document: { title: "" }, addEventListener() {},
        console: {
            log() {},
            warn(...a) { warnings.push(a.map(x => String(x)).join(" ")); },
            error(...a) { errors.push(a.map(x => (x && x.stack) || String(x)).join(" ")); }
        }
    };
    env.window = env;
    const sources = names.map(readPlugin);
    const classes = new Set(["Sprite", "Window_Base", "Window_Selectable", "Scene_Map", "Scene_Boot", "Rectangle", "Bitmap"]);
    const protoRe = /\b((?:Game|Scene|Window|Spriteset|Sprite)_[A-Za-z0-9_]+)\.prototype(?:\.([A-Za-z0-9_]+))?/g;
    for (const s of sources) for (const m of s.matchAll(protoRe)) classes.add(m[1]);
    for (const c of classes) env[c] = function() { throw new Error("Unexpected engine construction " + c); };
    for (const s of sources) for (const m of s.matchAll(protoRe)) {
        if (m[2]) env[m[1]].prototype[m[2]] = () => { throw new Error("Unexpected engine method " + m[1] + "." + m[2]); };
    }
    env.Scene_Boot.prototype.start = function() { throw new Error("boot stub after hooks"); };
    env.Bitmap.prototype = { clear() {}, fillRect() {}, strokeRect() {}, blt() {} };
    simHook.install(env);
    if (beforePlugins) beforePlugins(env);
    const ctx = vm.createContext(env);
    vm.runInContext(["Math", "Object", "Array", "Number", "String", "Boolean", "Map", "Set", "JSON", "Date",
        "Uint8Array", "Uint16Array", "Int8Array", "Int32Array", "Float32Array", "performance", "window"]
        .map(n => "const " + n + " = globalThis." + n + ";").join("\n"), ctx);
    vm.runInContext(TILEMAP_SRC, ctx, { filename: "rmmz_core.js#Tilemap-statics" });
    names.forEach((n, i) => vm.runInContext(sources[i], ctx, { filename: n + ".js" }));
    env._warnings = warnings;
    env._errors = errors;
    return env;
}

function boot(env) {
    let threw = null;
    try { env.Scene_Boot.prototype.start.call(env); }
    catch (e) { threw = e && e.message ? e.message : String(e); }
    return threw;
}

function openWorld(env, seed) {
    const t0 = performance.now();
    let st = null, err = null;
    try { st = env.UF.World.newWorld(seed); }
    catch (e) { err = e && e.stack ? e.stack : String(e); }
    return { st, ms: performance.now() - t0, err };
}

const results = [];
function check(name, pass, detail) {
    const line = String(detail || "").replace(/\s+/g, " ").slice(0, 1200);
    results.push({ name, pass: !!pass });
    console.log((pass ? "PASS " : "FAIL ") + name + ": " + line);
}

function median(xs) {
    if (!xs.length) return 0;
    const s = xs.slice().sort((a, b) => a - b);
    const m = Math.floor(s.length / 2);
    return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
}

function areaKey(ax, ay) { return ax + "," + ay; }

function homesOf(st) {
    const list = st && st.factions && st.factions.list || [];
    return list.map(f => ({
        x: f.home && f.home.area ? f.home.area.x : null,
        y: f.home && f.home.area ? f.home.area.y : null,
        z: f.home ? f.home.z : null,
        species: f.species,
        player: !!f.isPlayer
    }));
}

function sumsOf(L, ax, ay) {
    const out = {};
    for (const z of CORE) out[String(z)] = L.areaChecksum(z, ax, ay);
    return out;
}

let run1 = null;
let run3 = null;

function fullRun(areas, seed, traceOn) {
    const env = makeEnv(areas, NEW_GAME_PLUGINS);
    const bootMsg = boot(env);
    const L = env.UF.Levels;
    if (traceOn && L && typeof L.traceAreaRequests === "function") L.traceAreaRequests(true);
    const opened = openWorld(env, seed);
    const stats = L && L.stats ? L.stats() : {};
    return { env, bootMsg, opened, stats, areas, seed, traceOn };
}

function ensureRun() {
    if (!shouldRun("ensure_generates_start_area_only") && !shouldRun("per_area_checksum_on_first_generation")
        && !shouldRun("area_sums_computed_once_per_area") && !shouldRun("per_area_checksum_mismatch_reported")) return null;
    const env = makeEnv(3, LEVELS_PLUGINS);
    const bootMsg = boot(env);
    const opened = openWorld(env, 18);
    return { env, bootMsg, opened };
}

function runEnsure(box) {
    const name = "ensure_generates_start_area_only";
    if (!shouldRun(name)) return;
    if (!box || box.opened.err || !box.opened.st) {
        check(name, false, "world did not open: " + (box && box.opened.err));
        return;
    }
    const st = box.opened.st;
    const stats = box.env.UF.Levels.stats();
    const gens = stats.areaGenerations || [];
    const pass = st.areasX === 3 && st.areasY === 3 && st.startArea && st.startArea.x === 1 && st.startArea.y === 1
        && gens.length === 1 && gens[0].ax === 1 && gens[0].ay === 1 && stats.generated === 5;
    check(name, pass, "grid " + st.areasX + "x" + st.areasY + " start " + JSON.stringify(st.startArea)
        + " areaGenerations " + JSON.stringify(gens) + " generated " + stats.generated + " (want exactly 1,1 and 5) boot " + box.bootMsg);
}

function runPerArea(box) {
    const name = "per_area_checksum_on_first_generation";
    if (!shouldRun(name)) return;
    const L = box && box.env && box.env.UF.Levels;
    if (!box || box.opened.err || !L || typeof L.areaChecksum !== "function") {
        check(name, false, "areaChecksum is not a function");
        return;
    }
    const st = box.opened.st;
    const problems = [];
    for (const z of CORE) {
        const Lz = st.levels[String(z)];
        const saved = Lz && Lz.areaSums && Lz.areaSums["1,1"];
        const now = L.areaChecksum(z, 1, 1);
        if (saved !== now || !now || now === "n/a") problems.push(z + " saved " + saved + " now " + now);
    }
    L.baseline(0, 0, 0);
    for (const z of CORE) {
        const Lz = st.levels[String(z)];
        if (!Lz || !Lz.areaSums || Lz.areaSums["0,0"] !== L.areaChecksum(z, 0, 0)) problems.push(z + " missing 0,0");
        if (Lz && Lz.areaSums && Object.prototype.hasOwnProperty.call(Lz.areaSums, "2,2")) problems.push(z + " recorded unrequested 2,2");
    }
    L.baseline(10, 1, 1);
    if (st.levels["10"] || st.levels["-10"]) problems.push("outer level gained an entry");
    const round = JSON.parse(JSON.stringify(st.levels));
    for (const z of CORE) {
        const live = st.levels[String(z)].areaSums;
        const copy = round[String(z)] && round[String(z)].areaSums;
        if (JSON.stringify(live) !== JSON.stringify(copy)) problems.push(z + " round trip lost areaSums");
    }
    check(name, problems.length === 0, problems.length ? problems.join("; ") : "start 1,1 and requested 0,0 recorded on the core; 2,2 and outer levels absent; JSON kept the sums");
}

function runOnce(box) {
    const name = "area_sums_computed_once_per_area";
    if (!shouldRun(name)) return;
    const L = box && box.env && box.env.UF.Levels;
    if (!L || !L.stats) { check(name, false, "no stats"); return; }
    const before = L.stats().areaSumComputations || 0;
    for (let i = 0; i < 1000; i++) L.baseline(0, 1, 1);
    const after = L.stats().areaSumComputations || 0;
    check(name, before === 1 && after === 1, "areaSumComputations before extra calls " + before + " after 1000 " + after + " (want 1 and 1)");
}

function runMismatch(box) {
    const name = "per_area_checksum_mismatch_reported";
    if (!shouldRun(name)) return;
    const L = box && box.env && box.env.UF.Levels;
    const st = box && box.opened.st;
    if (!L || !st || !st.levels["0"] || !st.levels["0"].areaSums) {
        check(name, false, "no area sum to corrupt");
        return;
    }
    const corrupt = JSON.parse(JSON.stringify(st));
    const prev = corrupt.levels["0"].areaSums["1,1"];
    const corrupted = prev.slice(0, 7) + (prev[7] === "0" ? "1" : "0");
    corrupt.levels["0"].areaSums["1,1"] = corrupted;
    const warns = box.env._warnings.length;
    box.env.DataManager.extractSaveContents({ ufWorld: corrupt });
    const loaded = box.env.UF.World.state;
    L.baseline(0, 1, 1);
    const now = loaded.levels["0"].areaSums["1,1"];
    const flagged = !!loaded.levels["0"].checksumMismatch;
    const warned = box.env._warnings.length > warns;
    const pass = now === corrupted && flagged && warned;
    check(name, pass, "saved " + now + " corrupted " + corrupted + " original " + prev
        + " flagged " + flagged + " warned " + warned);
}

function runEventOnce() {
    const name = "area_generated_event_once";
    if (!shouldRun(name)) return;
    const env = makeEnv(1, LEVELS_PLUGINS);
    const events = [];
    boot(env);
    if (env.UF.Events && env.UF.Events.on) env.UF.Events.on("levels:areaGenerated", p => events.push({ ax: p.ax, ay: p.ay, gen: p.gen }));
    const first = openWorld(env, 18);
    if (first.err) { check(name, false, first.err.split("\n")[0]); return; }
    const afterA = events.length;
    const stateA = env.UF.World.state;
    env.UF.Levels.baseline(0, 0, 0);
    const afterRepeat = events.length;
    if (afterA !== 1 || afterRepeat !== 1) {
        check(name, false, "events after first world " + afterA + " after repeat " + afterRepeat + " (want 1 and 1) " + JSON.stringify(events));
        return;
    }
    const second = openWorld(env, 18);
    if (second.err) { check(name, false, second.err.split("\n")[0]); return; }
    const afterB = events.length;
    if (afterB !== 2) {
        check(name, false, "events after a second world of the same seed " + afterB + " (want 2; a cached volume still records the new state)");
        return;
    }
    for (let i = 0; i < 14; i++) {
        const opened = openWorld(env, 1000 + i);
        if (opened.err) { check(name, false, "eviction world " + i + " " + opened.err.split("\n")[0]); return; }
    }
    const beforeRegen = events.length;
    env.UF.World.state = stateA;
    env.UF.Levels.baseline(0, 0, 0);
    const pass = events.length === beforeRegen && events[0].ax === 0 && events[0].ay === 0;
    check(name, pass, "first " + afterA + " repeat " + afterRepeat + " new state " + afterB + " after eviction regen " + events.length + " (no extra) before " + beforeRegen);
}

function runDeferred() {
    const name = "area_generated_deferred_on_load";
    if (!shouldRun(name)) return;
    let phase = "boot";
    const env = makeEnv(3, LEVELS_PLUGINS, sandbox => {
        const prev = sandbox.DataManager.extractSaveContents;
        sandbox.DataManager.extractSaveContents = function(contents) {
            phase = "inner";
            const L = sandbox.UF && sandbox.UF.Levels;
            const W = sandbox.UF && sandbox.UF.World;
            if (L && W && W.state) {
                L.baseline(0, 0, 0);
                L.baseline(0, 0, 0);
                L.baseline(0, 0, 1);
                L.baseline(0, 2, 2);
            }
            phase = "inner-done";
            if (prev) prev.call(this, contents);
        };
    });
    boot(env);
    const opened = openWorld(env, 18);
    if (opened.err) { check(name, false, opened.err.split("\n")[0]); return; }
    const delivered = [];
    let duringInner = 0;
    env.UF.Events.on("levels:areaGenerated", p => {
        if (phase === "inner") duringInner++;
        delivered.push({ ax: p.ax, ay: p.ay, gen: p.gen, marker: env.UF.World.state && env.UF.World.state._loadMarker || "" });
    });
    const loaded = JSON.parse(JSON.stringify(env.UF.World.state));
    loaded._loadMarker = "loaded";
    phase = "extract";
    env.DataManager.extractSaveContents({ ufWorld: loaded });
    phase = "after";
    const order = delivered.map(e => e.ax + "," + e.ay).join(" ");
    const markersOk = delivered.length > 0 && delivered.every(e => e.marker === "loaded");
    const pass = duringInner === 0 && order === "0,0 0,1 2,2" && markersOk && env.UF.World.state && env.UF.World.state._loadMarker === "loaded";
    check(name, pass, "during inner " + duringInner + " order [" + order + "] markers " + markersOk + " state " + (env.UF.World.state && env.UF.World.state._loadMarker));
}

function runOffscreen() {
    const name = "offscreen_request_generates_area";
    if (!shouldRun(name)) return;
    const env = makeEnv(3, LEVELS_PLUGINS);
    boot(env);
    const opened = openWorld(env, 18);
    if (opened.err || !opened.st) { check(name, false, opened.err || "no world"); return; }
    const L = env.UF.Levels;
    if (!L || typeof L.traceAreaRequests !== "function") { check(name, false, "traceAreaRequests is not a function"); return; }
    L.traceAreaRequests(true);
    const st = opened.st;
    env.$gameMap._mapId = env.UF.World.areaMapId(st.startArea.x, st.startArea.y, 0);
    const view = env.UF.World.viewLevel();
    const before = L.stats().generated;
    vm.runInContext("globalThis.__offscreenBaseline = UF.Levels.baseline(0, 0, 0);", env, { filename: "DEUS_Factions.js" });
    const b = env.__offscreenBaseline;
    const stats = L.stats();
    const req = (stats.areaRequests || []).find(r => r.ax === 0 && r.ay === 0);
    const pass = !!b && !!b.shape && b.shape.length === st.size * st.size && !!req && req.requester === "DEUS_Factions.js"
        && stats.generated === before + 5 && view && view.x === 1 && view.y === 1 && !(view.x === 0 && view.y === 0);
    check(name, pass, "view " + JSON.stringify(view) + " baseline " + (b ? "yes" : "null") + " requester " + (req && req.requester)
        + " generated " + before + " -> " + stats.generated + " requests " + JSON.stringify(stats.areaRequests));
}

function runLegacy() {
    const name = "legacy_single_checksum_verifies";
    if (!shouldRun(name)) return;
    const chain1 = dcChain(18, 1);
    const chain3 = dcChain(18, 3);
    function plant(areas, chain) {
        const env = makeEnv(areas, LEVELS_PLUGINS);
        boot(env);
        const opened = openWorld(env, 18);
        if (opened.err || !opened.st) return { err: opened.err || "no world" };
        const st = opened.st;
        for (const z of CORE) {
            const Lz = st.levels[String(z)];
            if (!Lz) return { err: "missing level " + z };
            Lz.checksum = chain[String(z)];
            delete Lz.areaSums;
        }
        const save = JSON.parse(JSON.stringify(st));
        const warns = env._warnings.length;
        const bad = env.UF.Levels.verifyLevels(save);
        env.UF.World.state = save;
        const mismatch = CORE.some(z => save.levels[String(z)].checksumMismatch);
        return { env, save, bad, mismatch, warns, stats: env.UF.Levels.stats() };
    }
    const one = plant(1, chain1);
    const three = plant(3, chain3);
    if (one.err || three.err) { check(name, false, (one.err || "") + " " + (three.err || "")); return; }
    const flipped = JSON.parse(JSON.stringify(three.save));
    const stored = flipped.levels["0"].checksum;
    flipped.levels["0"].checksum = stored.slice(0, 7) + (stored[7] === "a" ? "b" : "a");
    const flippedStored = flipped.levels["0"].checksum;
    const warns = three.env._warnings.length;
    three.env.UF.World.state = flipped;
    const badFlip = three.env.UF.Levels.verifyLevels(flipped);
    const kept = flipped.levels["0"].checksum === flippedStored;
    const flagged = !!flipped.levels["0"].checksumMismatch;
    const warned = three.env._warnings.length > warns;
    let equal = true;
    if (typeof one.env.UF.Levels.areaChecksum === "function") {
        one.env.UF.World.state = one.save;
        for (const z of CORE) {
            if (one.env.UF.Levels.areaChecksum(z, 0, 0) !== one.env.UF.Levels.checksum(z)) equal = false;
        }
    }
    const pass = one.bad.length === 0 && !one.mismatch && three.bad.length === 0 && !three.mismatch
        && badFlip.length > 0 && kept && flagged && warned && equal;
    check(name, pass, "1x1 mismatches " + one.bad.length + " 3x3 mismatches " + three.bad.length
        + " flipped reported " + badFlip.length + " kept " + kept + " flagged " + flagged + " warned " + warned
        + " one-area areaChecksum equals checksum " + equal);
}

function runLegacyMigration() {
    const name = "legacy_multi_area_migrates_after_verify";
    if (!shouldRun(name)) return;
    const env = makeEnv(3, LEVELS_PLUGINS);
    boot(env);
    const opened = openWorld(env, 18);
    if (opened.err || !opened.st) { check(name, false, opened.err || "no world"); return; }
    const legacy = JSON.parse(JSON.stringify(opened.st));
    const chain = dcChain(18, 3);
    for (const z of CORE) {
        const entry = legacy.levels[String(z)];
        entry.checksum = chain[String(z)];
        delete entry.areaSums;
    }
    env.DataManager.extractSaveContents({ ufWorld: JSON.parse(JSON.stringify(legacy)) });
    const migrated = env.UF.World.state;
    const fixture = JSON.parse(fs.readFileSync(AREA_FIXTURE, "utf8"));
    const frozen = fixture.cases.find(c => c.seed === 18);
    let sumsMatch = !!frozen;
    for (const z of CORE) {
        const sums = migrated.levels[String(z)].areaSums;
        if (!sums || Object.keys(sums).length !== 9) { sumsMatch = false; continue; }
        for (const area of frozen.areas) {
            if (sums[areaKey(area.x, area.y)] !== area.sums[String(z)]) sumsMatch = false;
        }
    }
    const migrationCount = st => (st.migrations || []).filter(m => m && m.rule === "WG.00.46").length;
    const oneMigration = migrationCount(migrated) === 1;
    env.DataManager.extractSaveContents({ ufWorld: JSON.parse(JSON.stringify(migrated)) });
    const stillOne = migrationCount(env.UF.World.state) === 1;

    const bad = JSON.parse(JSON.stringify(legacy));
    const stored = bad.levels["0"].checksum;
    bad.levels["0"].checksum = stored.slice(0, 7) + (stored[7] === "0" ? "1" : "0");
    const warningsBefore = env._warnings.length;
    env.DataManager.extractSaveContents({ ufWorld: bad });
    const rejected = env.UF.World.state;
    const mismatchHeld = rejected.levels["0"].checksum === bad.levels["0"].checksum
        && rejected.levels["0"].checksumMismatch === true
        && CORE.every(z => !rejected.levels[String(z)].areaSums)
        && migrationCount(rejected) === 0 && env._warnings.length > warningsBefore;
    check(name, sumsMatch && oneMigration && stillOne && mismatchHeld,
        "frozen area sums " + sumsMatch + " first migration " + oneMigration
        + " idempotent " + stillOne + " mismatch kept without migration " + mismatchHeld);
}

function runLoadVisited() {
    const name = "load_generates_visited_areas_only";
    if (!shouldRun(name)) return;
    const maker = makeEnv(3, LEVELS_PLUGINS);
    boot(maker);
    const made = openWorld(maker, 18);
    if (made.err || !made.st) { check(name, false, made.err || "no world"); return; }
    maker.UF.Levels.baseline(0, 0, 0);
    const save = JSON.parse(JSON.stringify(maker.UF.World.state));
    const recorded = [];
    for (const z of CORE) {
        const sums = save.levels[String(z)] && save.levels[String(z)].areaSums || {};
        for (const k of Object.keys(sums)) if (recorded.indexOf(k) < 0) recorded.push(k);
    }
    const loader = makeEnv(3, LEVELS_PLUGINS);
    boot(loader);
    const before = loader.UF.Levels.stats().generated;
    let extractErr = null;
    try { loader.DataManager.extractSaveContents({ ufWorld: save }); }
    catch (e) { extractErr = e && e.stack ? e.stack : String(e); }
    const afterExtract = loader.UF.Levels.stats().generated;
    let buildErr = null;
    try { loader.DataManager.loadMapData(loader.UF.World.areaMapId(0, 0, 0)); }
    catch (e) { buildErr = e && e.message ? e.message : String(e); }
    const stats = loader.UF.Levels.stats();
    const gens = stats.areaGenerations || [];
    const keys = gens.map(g => areaKey(g.ax, g.ay));
    const unique = new Set(keys);
    const pass = !extractErr && !buildErr && afterExtract === before && unique.size === 1 && unique.has("0,0") && stats.generated - before <= 5
        && recorded.indexOf("0,0") >= 0 && recorded.indexOf("1,1") >= 0;
    check(name, pass, "recorded " + recorded.join(" ") + " extract generated delta " + (afterExtract - before)
        + " after build " + JSON.stringify(keys) + " generated delta " + (stats.generated - before)
        + (extractErr ? " extract " + extractErr.split("\n")[0] : "") + (buildErr ? " build " + buildErr : ""));
}

function gridAreas() {
    const areas = [];
    for (let y = 0; y < 3; y++) for (let x = 0; x < 3; x++) areas.push({ x, y });
    return areas;
}

function orderAreas(kind, seed) {
    const areas = gridAreas();
    const start = { x: 1, y: 1 };
    if (kind === "start-first") {
        return [start].concat(areas.filter(a => !(a.x === 1 && a.y === 1)));
    }
    if (kind === "reverse") return areas.slice().reverse();
    if (kind === "shuffle") {
        const a = areas.slice();
        let s = seed >>> 0;
        for (let i = a.length - 1; i > 0; i--) {
            s = Math.imul(s, 1664525) + 1013904223 >>> 0;
            const j = s % (i + 1);
            const t = a[i]; a[i] = a[j]; a[j] = t;
        }
        return a;
    }
    return areas.filter(a => !(a.x === 1 && a.y === 1)).concat([start]);
}

function runLazy() {
    const name = "lazy_equals_eager";
    if (!shouldRun(name)) return;
    const probe = makeEnv(3, LEVELS_PLUGINS);
    if (typeof probe.UF.Levels.areaChecksum !== "function") {
        check(name, false, "areaChecksum is not a function");
        return;
    }
    const seeds = [18, 20260927];
    const cases = [];
    const problems = [];
    for (const seed of seeds) {
        const env = makeEnv(3, LEVELS_PLUGINS);
        boot(env);
        const opened = openWorld(env, seed);
        if (opened.err || !opened.st) { check(name, false, "seed " + seed + " " + (opened.err || "no world")); return; }
        const L = env.UF.Levels;
        const st = opened.st;
        const want = dcChain(seed, 3);
        const chain = {};
        for (const z of CORE) {
            chain[String(z)] = L.checksum(z);
            if (chain[String(z)] !== want[String(z)]) problems.push("seed " + seed + " z " + z + " chain " + chain[String(z)] + " != dc " + want[String(z)]);
        }
        const desc = {
            seed: st.seed, size: st.size, areasX: 3, areasY: 3,
            startArea: { x: st.startArea.x, y: st.startArea.y },
            verticalBiomeCoupling: true,
            zRange: { zMin: st.zRange.zMin, zMax: st.zRange.zMax }
        };
        const orders = {
            "start-first": orderAreas("start-first", seed),
            reverse: orderAreas("reverse", seed),
            shuffle: orderAreas("shuffle", seed),
            "start-last": orderAreas("start-last", seed)
        };
        const byOrder = {};
        for (const kind of Object.keys(orders)) {
            const sums = {};
            for (const a of orders[kind]) {
                const key = areaKey(a.x, a.y);
                sums[key] = {};
                for (const z of CORE) {
                    sums[key][String(z)] = kind === "start-last"
                        ? L.areaChecksum(z, a.x, a.y, seed, 5, desc)
                        : L.areaChecksum(z, a.x, a.y);
                }
            }
            byOrder[kind] = sums;
        }
        const canonical = sums => gridAreas().map(a => areaKey(a.x, a.y) + "=" + JSON.stringify(sums[areaKey(a.x, a.y)])).join(";");
        const first = canonical(byOrder["start-first"]);
        for (const kind of Object.keys(byOrder)) {
            if (canonical(byOrder[kind]) !== first) problems.push("seed " + seed + " order " + kind + " differs from start-first");
        }
        const areas = gridAreas().map(a => ({ x: a.x, y: a.y, sums: byOrder["start-first"][areaKey(a.x, a.y)] }));
        cases.push({ seed, startArea: { x: 1, y: 1 }, areas, chain });
    }
    let fixture = null;
    if (fs.existsSync(AREA_FIXTURE)) fixture = JSON.parse(fs.readFileSync(AREA_FIXTURE, "utf8"));
    if (fixture) {
        for (const c of cases) {
            const fc = (fixture.cases || []).find(x => x.seed === c.seed);
            if (!fc) { problems.push("fixture missing seed " + c.seed); continue; }
            for (const a of c.areas) {
                const fa = (fc.areas || []).find(x => x.x === a.x && x.y === a.y);
                if (!fa || JSON.stringify(fa.sums) !== JSON.stringify(a.sums)) problems.push("seed " + c.seed + " area " + a.x + "," + a.y + " != fixture");
            }
        }
    } else if (!capture) {
        problems.push("fixture missing (run --capture-fixture once the chain matches)");
    }
    if (capture) {
        if (problems.length) {
            check(name, false, "not captured: " + problems.join("; "));
            return;
        }
        let sha = "";
        try { sha = execFileSync("git", ["rev-parse", "HEAD"], { cwd: ROOT, encoding: "utf8" }).trim(); }
        catch (e) { sha = ""; }
        const body = {
            sourceSha: sha,
            capturedOn: new Date().toISOString().slice(0, 10),
            generator: 5,
            areasX: 3,
            areasY: 3,
            zRange: { zMin: -16, zMax: 15 },
            size: 256,
            verticalBiomeCoupling: true,
            coreLevels: CORE.slice(),
            note: "Per-area generator-5 core checksums at 3x3. Captured after the all-area chain matched tools/fixtures/levels/core_checksums_gen1_5.json. One area's ground sum is lattice then strata, which is the one-area order, not a slice of the all-area chain.",
            cases
        };
        fs.writeFileSync(AREA_FIXTURE, JSON.stringify(body, null, 2) + "\n");
        console.log("CAPTURE wrote " + AREA_FIXTURE);
    }
    check(name, problems.length === 0, problems.length ? problems.slice(0, 4).join("; ") : "seeds 18 and 20260927, four orders, chain matches lane-dc, sums match the area fixture");
}

function runFullChecks() {
    const need1 = shouldRun("new_game_3x3_cost_bound") || shouldRun("trace_off_by_default");
    const need3 = shouldRun("new_game_3x3_areas_attributed") || shouldRun("new_game_3x3_cost_bound") || shouldRun("home_areas_exist_at_tick0");
    if (need1) run1 = fullRun(1, 424242, false);
    if (need3) run3 = fullRun(3, 424242, true);

    if (shouldRun("trace_off_by_default")) {
        if (!run1 || run1.opened.err) check("trace_off_by_default", false, run1 ? run1.opened.err.split("\n")[0] : "no 1x1 run");
        else {
            const stats = run1.stats;
            const L = run1.env.UF.Levels;
            const flag = L && typeof L.traceAreaRequests === "function" ? L.traceAreaRequests() : false;
            const reqs = stats.areaRequests || [];
            const reads = stats.areaStackReads || 0;
            check("trace_off_by_default", flag === false && reqs.length === 0 && reads === 0,
                "trace " + flag + " areaRequests " + reqs.length + " areaStackReads " + reads);
        }
    }

    if (shouldRun("home_areas_exist_at_tick0")) {
        if (!run3 || run3.opened.err || !run3.opened.st) check("home_areas_exist_at_tick0", false, run3 && run3.opened.err ? run3.opened.err.split("\n")[0] : "no 3x3 world");
        else {
            const st = run3.opened.st;
            const homes = homesOf(st);
            const L = run3.env.UF.Levels;
            const before = L.stats().generated;
            let readable = true;
            for (const h of homes) {
                const b = L.baseline(h.z, h.x, h.y);
                if (!b || !b.shape || !b.shape.length) readable = false;
            }
            const tick = run3.env.UF.Sim && run3.env.UF.Sim.tickCount ? run3.env.UF.Sim.tickCount() : -1;
            const noNew = L.stats().generated === before;
            check("home_areas_exist_at_tick0", tick === 0 && readable && noNew && homes.length > 0,
                "tick " + tick + " homes " + homes.length + " readable " + readable + " generated stayed " + noNew
                + " " + homes.map(h => h.species + "@" + h.x + "," + h.y + " z" + h.z).join(" "));
        }
    }

    if (shouldRun("new_game_3x3_areas_attributed")) {
        if (!run3 || run3.opened.err || !run3.opened.st) check("new_game_3x3_areas_attributed", false, run3 && run3.opened.err ? run3.opened.err.split("\n")[0] : "no 3x3 world");
        else {
            const st = run3.opened.st;
            const gens = run3.stats.areaGenerations || [];
            const reqs = run3.stats.areaRequests || [];
            const homes = homesOf(st);
            const start = st.startArea || { x: 1, y: 1 };
            const predicate = list => {
                const keys = list.map(g => areaKey(g.ax, g.ay));
                if (new Set(keys).size !== keys.length) return false;
                if (keys.indexOf(areaKey(start.x, start.y)) < 0) return false;
                for (const g of list) {
                    const k = areaKey(g.ax, g.ay);
                    if (k === areaKey(start.x, start.y)) continue;
                    const req = reqs.find(r => r.ax === g.ax && r.ay === g.ay);
                    if (!req || !req.requester || req.requester === "DEUS_Levels.js" || req.requester === "UF_Levels.js") return false;
                    if (!homes.some(h => h.x === g.ax && h.y === g.ay)) return false;
                }
                const holds10 = homes.some(h => h.x === 1 && h.y === 0);
                if (keys.indexOf("1,0") >= 0 && !holds10) return false;
                return list.length > 0;
            };
            const realOk = predicate(gens);
            const oneDupOk = gens.length ? predicate(gens.concat([gens[0]])) : true;
            console.log("DEC-065 areas " + gens.map(g => {
                const req = reqs.find(r => r.ax === g.ax && r.ay === g.ay);
                return g.ax + "," + g.ay + " " + g.ms.toFixed(1) + "ms " + (req ? req.requester : "(no requester)");
            }).join(" | "));
            console.log("DEC-065 homes " + homes.map(h => h.species + (h.player ? "*" : "") + "@" + h.x + "," + h.y + " z" + h.z).join(" "));
            check("new_game_3x3_areas_attributed", realOk && !oneDupOk,
                "real " + realOk + " one-duplicate-would-pass " + oneDupOk + " areas " + gens.map(g => areaKey(g.ax, g.ay)).join(" "));
        }
    }

    if (shouldRun("new_game_3x3_cost_bound")) {
        const wall1 = run1 && run1.opened ? run1.opened.ms : 0;
        const wall3 = run3 && run3.opened ? run3.opened.ms : 0;
        const g1 = run1 && run1.stats && run1.stats.areaGenerations;
        const g3 = run3 && run3.stats && run3.stats.areaGenerations;
        const grid1 = run1 && run1.opened.st ? run1.opened.st.areasX + "x" + run1.opened.st.areasY : "?";
        const grid3 = run3 && run3.opened.st ? run3.opened.st.areasX + "x" + run3.opened.st.areasY : "?";
        if (!Array.isArray(g1) || !Array.isArray(g3)) {
            console.log("DEC-065 T(1x1) " + wall1.toFixed(0) + " ms grid " + grid1 + "; T(3x3) " + wall3.toFixed(0) + " ms grid " + grid3 + "; areaGenerations absent, whole-run times printed only");
            check("new_game_3x3_cost_bound", !!(run1 && run3 && !run1.opened.err && !run3.opened.err),
                "areaGenerations absent; T(1x1) " + wall1.toFixed(0) + " ms T(3x3) " + wall3.toFixed(0) + " ms");
        } else {
            const ms = g3.map(g => g.ms);
            const unique = new Set(g3.map(g => areaKey(g.ax, g.ay)));
            const k = unique.size;
            const tarea = median(ms);
            const sum = ms.reduce((a, b) => a + b, 0);
            const t1levels = g1.reduce((a, g) => a + g.ms, 0);
            const limit = t1levels + k * tarea;
            const dec = wall1 + (k - 1) * tarea * 1.25;
            console.log("DEC-065 T(1x1) " + wall1.toFixed(1) + " ms grid " + grid1
                + " T(3x3) " + wall3.toFixed(1) + " ms grid " + grid3
                + " k " + k + " Tarea " + tarea.toFixed(1) + " ms"
                + " per-area " + ms.map(v => v.toFixed(1)).join(",")
                + " T1x1_levels " + t1levels.toFixed(1)
                + " judged sum " + sum.toFixed(1) + " <= " + limit.toFixed(1)
                + " printed expression T(1x1)+(k-1)*Tarea*1.25 = " + dec.toFixed(1));
            check("new_game_3x3_cost_bound", sum <= limit + 1e-6,
                "Levels sum " + sum.toFixed(1) + " ms limit " + limit.toFixed(1) + " ms (T1x1_levels " + t1levels.toFixed(1) + " + k " + k + " * Tarea " + tarea.toFixed(1) + ")");
        }
    }
}

const t0 = performance.now();
console.log("lazy area generation" + (mutant ? " mutant " + mutant : "") + (fromRev ? " from-rev " + fromRev : "") + (capture ? " capture" : ""));
try {
    const shared = ensureRun();
    if (shared) {
        runEnsure(shared);
        runOnce(shared);
        runPerArea(shared);
        runMismatch(shared);
    }
    runEventOnce();
    runDeferred();
    runOffscreen();
    runLegacy();
    runLegacyMigration();
    runLoadVisited();
    runFullChecks();
    runLazy();
} catch (e) {
    harnessDie(e && e.stack ? e.stack : String(e));
}

const elapsed = (performance.now() - t0) / 1000;
const failed = results.filter(r => !r.pass);
console.log("TIME " + elapsed.toFixed(1) + " s (target " + TARGET_S + " s, printed, not a failing check)");
console.log("RESULT " + (results.length - failed.length) + " passed, " + failed.length + " failed" + (failed.length ? " (" + failed.map(r => r.name).join(", ") + ")" : ""));
process.exit(failed.length ? 1 : 0);
